query getPolicies($accountId: Int!, $cursor: String) {
  actor {
    account(id: $accountId) {
      alerts {
        policiesSearch(cursor: $cursor) {
          policies {
            id
            accountId
            name
            incidentPreference
          }
          nextCursor
        }
      }
    }
  }
}