query getPolicyConditions($accountId: Int!, $policyId: ID!, $cursor: String) {
  actor {
    account(id: $accountId) {
      alerts {
        nrqlConditionsSearch(cursor: $cursor, searchCriteria: {policyId: $policyId}) {
          nextCursor
          nrqlConditions {
            name
            description
            nrql {
              query
              evaluationOffset
            }
            enabled
            id
            expiration {
              openViolationOnExpiration
              expirationDuration
              closeViolationsOnExpiration
            }
            runbookUrl
            policyId
            signal {
              aggregationDelay
              aggregationMethod
              aggregationTimer
              aggregationWindow
              evaluationDelay
              fillOption
              fillValue
              slideBy
            }
            terms {
              operator
              priority
              threshold
              thresholdDuration
              thresholdOccurrences
            }
            type
            violationTimeLimitSeconds
          }
          totalCount
        }
      }
    }
  }
}