query getPolicyConditions($accountId: Int!, $policyId: ID!, $cursor: String) {
  actor {
    account(id: $accountId) {
      alerts {
        nrqlConditionsSearch(cursor: $cursor, searchCriteria: {policyId: $policyId}) {
          nextCursor
          nrqlConditions {
            name
            description
            nrql {
              query
              evaluationOffset
            }
            enabled
            id
          }
          totalCount
        }
      }
    }
  }
}